package com.example.syncfit.ui.theme

import androidx.compose.ui.graphics.Color

val md_theme_light_primary = Color(0xFF3A6A1D)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFFBAF295)
val md_theme_light_onPrimaryContainer = Color(0xFF092100)
//val md_theme_light_secondary = Color(0xFF376A20)
val md_theme_light_secondary = Color(0xFF55624c) // Manual Intervention
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFFB7F397)
val md_theme_light_onSecondaryContainer = Color(0xFF072100)
val md_theme_light_tertiary = Color(0xFF00696C)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
//val md_theme_light_tertiaryContainer = Color(0xFF6FF6FA)
val md_theme_light_tertiaryContainer = Color(0xFFBDEAF3) // Manual Intervention
val md_theme_light_onTertiaryContainer = Color(0xFF002021)
val md_theme_light_error = Color(0xFFBA1A1A)
val md_theme_light_errorContainer = Color(0xFFFFDAD5)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_onErrorContainer = Color(0xFF410002)
val md_theme_light_background = Color(0xFFFCFDF6)
val md_theme_light_onBackground = Color(0xFF1A1C18)
val md_theme_light_outline = Color(0xFF73796E)
val md_theme_light_inverseOnSurface = Color(0xFFF1F1EB)
val md_theme_light_inverseSurface = Color(0xFF2F312D)
val md_theme_light_inversePrimary = Color(0xFF9FD67C)
val md_theme_light_surfaceTint = Color(0xFF3A6A1D)
val md_theme_light_outlineVariant = Color(0xFFC3C8BB)
val md_theme_light_scrim = Color(0xFF000000)
val md_theme_light_surface = Color(0xFFF9FAF3)
val md_theme_light_onSurface = Color(0xFF1A1C18)
val md_theme_light_surfaceVariant = Color(0xFFDFE4D7)
val md_theme_light_onSurfaceVariant = Color(0xFF43483F)

val md_theme_dark_primary = Color(0xFF9FD67C)
val md_theme_dark_onPrimary = Color(0xFF143800)
val md_theme_dark_primaryContainer = Color(0xFF225104)
val md_theme_dark_onPrimaryContainer = Color(0xFFBAF295)
//val md_theme_dark_secondary = Color(0xFF9CD67E)
val md_theme_dark_secondary = Color(0xFFBDCBB0) // Manual Intervention
//val md_theme_dark_onSecondary = Color(0xFF103800)
val md_theme_dark_onSecondary = Color(0xFF283420) // Manual Intervention
val md_theme_dark_secondaryContainer = Color(0xFF205107)
val md_theme_dark_onSecondaryContainer = Color(0xFFB7F397)
val md_theme_dark_tertiary = Color(0xFF4CDADD)
val md_theme_dark_onTertiary = Color(0xFF003738)
val md_theme_dark_tertiaryContainer = Color(0xFF004F51)
val md_theme_dark_onTertiaryContainer = Color(0xFF6FF6FA)
val md_theme_dark_error = Color(0xFFFFB4AB)
val md_theme_dark_errorContainer = Color(0xFF930009)
val md_theme_dark_onError = Color(0xFF690004)
val md_theme_dark_onErrorContainer = Color(0xFFFFDAD5)
val md_theme_dark_background = Color(0xFF1A1C18)
val md_theme_dark_onBackground = Color(0xFFE2E3DD)
val md_theme_dark_outline = Color(0xFF8D9287)
val md_theme_dark_inverseOnSurface = Color(0xFF1A1C18)
val md_theme_dark_inverseSurface = Color(0xFFE2E3DD)
val md_theme_dark_inversePrimary = Color(0xFF3A6A1D)
val md_theme_dark_surfaceTint = Color(0xFF9FD67C)
val md_theme_dark_outlineVariant = Color(0xFF43483F)
val md_theme_dark_scrim = Color(0xFF000000)
val md_theme_dark_surface = Color(0xFF121410)
val md_theme_dark_onSurface = Color(0xFFC6C7C1)
val md_theme_dark_surfaceVariant = Color(0xFF43483F)
val md_theme_dark_onSurfaceVariant = Color(0xFFC3C8BB)


val seed = Color(0xFF3A691E)
